#!/usr/bin/env bash
#
#  quarld The Quarlcoin server.
#
#
# chkconfig: 345 80 20
# description: quarld
# processname: quarld
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/quarld, see below
if [ -f /etc/sysconfig/quarld ]; then
        . /etc/sysconfig/quarld
fi

RETVAL=0

prog=quarld
# you can override the lockfile via QUARLD_LOCKFILE in /etc/sysconfig/quarld
lockfile=${QUARLD_LOCKFILE-/var/lock/subsys/quarld}

# quarld defaults to /usr/bin/quarld, override with QUARLD_BIN
quarld=${QUARLD_BIN-/usr/bin/quarld}

# quarld opts default to -disablewallet, override with QUARLD_OPTS
quarld_opts=${QUARLD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $quarld $quarld_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
